[package]
name = "space-acres"
description = "Space Acres is an opinionated unofficial GUI application for farming on Subspace Network"
license = "0BSD"
version = "0.0.1"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2021"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
anyhow = "1.0.75"
arc-swap = "1.6.0"
async-trait = "0.1.74"
atomic = "0.5.3"
bytesize = "1.3.0"
dirs = "5.0.1"
event-listener-primitives = "2.0.1"
futures = "0.3.29"
gtk = { version = "0.7.3", package = "gtk4" }
hex = "0.4.3"
# Substrate uses old version of libp2p
libp2p-identity-substate = { version = "0.1.3", package = "libp2p-identity" }
lru = "0.11.0"
mimalloc = "0.1.39"
names = "0.14.0"
parking_lot = "0.12.1"
relm4 = { version = "0.7.0-beta.2", git = "https://github.com/Relm4/Relm4.git", rev = "ef68be42a7f5ce253399a3f00b9a3d4e0fb682b7" }
relm4-components = { version = "0.7.0-beta.2", git = "https://github.com/Relm4/Relm4.git", rev = "ef68be42a7f5ce253399a3f00b9a3d4e0fb682b7", default-features = false }
sc-client-api = { git = "https://github.com/subspace/polkadot-sdk", rev = "892bf8e938c6bd2b893d3827d1093cd81baa59a1", default-features = false }
sc-client-db = { git = "https://github.com/subspace/polkadot-sdk", rev = "892bf8e938c6bd2b893d3827d1093cd81baa59a1", default-features = false }
sc-consensus-slots = { git = "https://github.com/subspace/polkadot-sdk", rev = "892bf8e938c6bd2b893d3827d1093cd81baa59a1", default-features = false }
sc-executor = { git = "https://github.com/subspace/polkadot-sdk", rev = "892bf8e938c6bd2b893d3827d1093cd81baa59a1", default-features = false }
sc-network = { git = "https://github.com/subspace/polkadot-sdk", rev = "892bf8e938c6bd2b893d3827d1093cd81baa59a1", default-features = false }
sc-service = { git = "https://github.com/subspace/polkadot-sdk", rev = "892bf8e938c6bd2b893d3827d1093cd81baa59a1", default-features = false }
sc-storage-monitor = { git = "https://github.com/subspace/polkadot-sdk", rev = "892bf8e938c6bd2b893d3827d1093cd81baa59a1", default-features = false }
sc-subspace-chain-specs = { git = "https://github.com/subspace/subspace.git", rev = "fc9c59b800d04b1fb9622fbf39f15d0e6420ee7e" }
serde = { version = "1.0.193", features = ["derive"]}
serde_json = "1.0.108"
sp-core = { git = "https://github.com/subspace/polkadot-sdk", rev = "892bf8e938c6bd2b893d3827d1093cd81baa59a1", default-features = false }
sp-consensus-subspace = { git = "https://github.com/subspace/subspace.git", rev = "fc9c59b800d04b1fb9622fbf39f15d0e6420ee7e" }
sp-domains-fraud-proof = { git = "https://github.com/subspace/subspace.git", rev = "fc9c59b800d04b1fb9622fbf39f15d0e6420ee7e" }
sp-runtime = { git = "https://github.com/subspace/polkadot-sdk", rev = "892bf8e938c6bd2b893d3827d1093cd81baa59a1", default-features = false }
subspace-core-primitives = { git = "https://github.com/subspace/subspace.git", rev = "fc9c59b800d04b1fb9622fbf39f15d0e6420ee7e" }
subspace-erasure-coding = { git = "https://github.com/subspace/subspace.git", rev = "fc9c59b800d04b1fb9622fbf39f15d0e6420ee7e" }
subspace-farmer = { git = "https://github.com/subspace/subspace.git", rev = "fc9c59b800d04b1fb9622fbf39f15d0e6420ee7e" }
subspace-farmer-components = { git = "https://github.com/subspace/subspace.git", rev = "fc9c59b800d04b1fb9622fbf39f15d0e6420ee7e" }
subspace-networking = { git = "https://github.com/subspace/subspace.git", rev = "fc9c59b800d04b1fb9622fbf39f15d0e6420ee7e" }
subspace-proof-of-space = { git = "https://github.com/subspace/subspace.git", rev = "fc9c59b800d04b1fb9622fbf39f15d0e6420ee7e" }
subspace-rpc-primitives = { git = "https://github.com/subspace/subspace.git", rev = "fc9c59b800d04b1fb9622fbf39f15d0e6420ee7e" }
subspace-runtime = { git = "https://github.com/subspace/subspace.git", rev = "fc9c59b800d04b1fb9622fbf39f15d0e6420ee7e" }
subspace-service = { git = "https://github.com/subspace/subspace.git", rev = "fc9c59b800d04b1fb9622fbf39f15d0e6420ee7e" }
supports-color = "2.0.0"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["fs", "time"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

# The list of dependencies below (which can be both direct and indirect dependencies) are crates
# that are suspected to be CPU-intensive, and that are unlikely to require debugging (as some of
# their debug info might be missing) or to require to be frequently recompiled. We compile these
# dependencies with `opt-level=3` even in "dev" mode in order to make "dev" mode more usable.
# The majority of these crates are cryptographic libraries.
#
# This list is ordered alphabetically.
[profile.dev.package]
bitvec = { opt-level = 3 }
blake2 = { opt-level = 3 }
blake3 = { opt-level = 3 }
blake2b_simd = { opt-level = 3 }
blst = { opt-level = 3 }
rust-kzg-blst = { opt-level = 3 }
chacha20 = { opt-level = 3 }
chacha20poly1305 = { opt-level = 3 }
cranelift-codegen = { opt-level = 3 }
cranelift-wasm = { opt-level = 3 }
crc32fast = { opt-level = 3 }
crossbeam-deque = { opt-level = 3 }
crypto-mac = { opt-level = 3 }
curve25519-dalek = { opt-level = 3 }
ed25519-zebra = { opt-level = 3 }
flate2 = { opt-level = 3 }
futures-channel = { opt-level = 3 }
hashbrown = { opt-level = 3 }
hash-db = { opt-level = 3 }
hmac = { opt-level = 3 }
httparse = { opt-level = 3 }
integer-sqrt = { opt-level = 3 }
k256 = { opt-level = 3 }
keccak = { opt-level = 3 }
kzg = { opt-level = 3 }
libsecp256k1 = { opt-level = 3 }
libz-sys = { opt-level = 3 }
mio = { opt-level = 3 }
nalgebra = { opt-level = 3 }
num-bigint = { opt-level = 3 }
parking_lot = { opt-level = 3 }
parking_lot_core = { opt-level = 3 }
percent-encoding = { opt-level = 3 }
primitive-types = { opt-level = 3 }
ring = { opt-level = 3 }
rustls = { opt-level = 3 }
secp256k1 = { opt-level = 3 }
sha2 = { opt-level = 3 }
sha3 = { opt-level = 3 }
smallvec = { opt-level = 3 }
snow = { opt-level = 3 }
subspace-archiving = { opt-level = 3 }
subspace-core-primitives = { opt-level = 3 }
subspace-erasure-coding = { opt-level = 3 }
subspace-farmer-components = { opt-level = 3 }
subspace-proof-of-space = { opt-level = 3 }
subspace-proof-of-time = { opt-level = 3 }
twox-hash = { opt-level = 3 }
uint = { opt-level = 3 }
x25519-dalek = { opt-level = 3 }
yamux = { opt-level = 3 }
zeroize = { opt-level = 3 }

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"

[profile.production]
inherits = "release"
lto = "fat"
